const Discord = require('discord.js');

function isEmpty (data) {
  if (
    data === null ||
    data === undefined ||
    data === '' ||
    data === [] ||
    data.length === 0 ||
    data === {}
    ) return true;
  return false;
}

function isISBN (text) {
  const updatedText = text.replace(/-/g, '');
  if (!isNaN(updatedText) && (updatedText.length === 13 || updatedText.length === 10)) {
    return true
  }
  return false
}

function embedMessage (options) {
  const setOptions = (
    {
    color = '#0099ff',
    title = '',
    url = 'https://discord.js.org/',
    author = 'The Librarian',
    authorImage = 'https://i.imgur.com/Rd3C6JY.jpg',
    authorLink = '',
    description = '',
    fields = [],
    thumbnail = 'https://i.imgur.com/mdrtrnP.jpeg',
    image = '',
    footer= 'Generated by The Librarian',
    footerImage = 'https://i.imgur.com/Rd3C6JY.jpg'
  }) => {
    return {
      color,
      title,
      url,
      author,
      authorImage,
      authorLink,
      description,
      fields,
      thumbnail,
      image,
      footer,
      footerImage
    }
  }
  
  // { name: 'Regular field title', value: 'Some value here' },
  // { name: '\u200B', value: '\u200B' },
  // { name: 'Inline field title', value: 'Some value here', inline: true },
  // { name: 'Inline field title', value: 'Some value here', inline: true },

  const messageOptions = setOptions(options);

  return new Discord.MessageEmbed()
  .setColor(messageOptions.color)
	.setTitle(messageOptions.title)
	.setURL(messageOptions.url)
	.setAuthor(messageOptions.author, messageOptions.authorImage, messageOptions.authorLink)
	.setDescription(messageOptions.description)
	.setThumbnail(messageOptions.thumbnail)
	.addFields(messageOptions.fields)
	.setImage(messageOptions.image)
	.setTimestamp()
	.setFooter(messageOptions.footer, messageOptions.footerImage);
}

module.exports = {
  isEmpty,
  isISBN,
  embedMessage
}